services:
  broker1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gomq_broker_1
    environment:
      - PEER_NODES=broker2,broker3
      - IS_LEADER=true
    depends_on:
      - broker2
      - broker3
    networks:
      - gomq_network

  broker2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gomq_broker_2
    networks:
      - gomq_network

  broker3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gomq_broker_3
    networks:
      - gomq_network

  nginx:
    image: nginx:latest
    container_name: gomq_nginx
    ports:
      - "50051:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - broker1
      - broker2
      - broker3
    networks:
      - gomq_network

networks:
  gomq_network:
    driver: bridge
