name: Common Checkout and Setup Go
description: Checks out the repository and sets up Go

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

inputs:
  go-version:
    description: "Version of Go to use"
    required: true
