name: Build and Release Go Binaries

on:
  push:
    branches:
      - master

permissions:
  contents: write # Grant write access to contents

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      mac-broker-binary: ${{ steps.build-broker-macos.outputs.binary-path }}
      linux-broker-binary: ${{ steps.build-broker-linux.outputs.binary-path }}
      windows-broker-binary: ${{ steps.build-broker-windows.outputs.binary-path }}
      mac-cli-binary: ${{ steps.build-cli-macos.outputs.binary-path }}
      linux-cli-binary: ${{ steps.build-cli-linux.outputs.binary-path }}
      windows-cli-binary: ${{ steps.build-cli-windows.outputs.binary-path }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Build macOS Broker Binary
        id: build-broker-macos
        run: |
          make build-broker-macos
          cp ./bin/broker-macos artifacts/
      - name: Build Linux Broker Binary
        id: build-broker-linux
        run: |
          make build-broker-linux
          cp ./bin/broker-linux artifacts/
      - name: Build Windows Broker Binary
        id: build-broker-windows
        run: |
          make build-broker
          cp ./bin/broker.exe artifacts/
      - name: Build macOS CLI Binary
        id: build-cli-macos
        run: |
          make build-cli-macos
          cp ./bin/cli-macos artifacts/
      - name: Build Linux CLI Binary
        id: build-cli-linux
        run: |
          make build-cli-linux
          cp ./bin/cli-linux artifacts/
      - name: Build Windows CLI Binary
        id: build-cli-windows
        run: |
          make build-cli
          cp ./bin/cli.exe artifacts/
      - name: Upload Binaries as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: artifacts/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Verify Protoc Installation
        run: protoc --version
      - name: Run Tests
        run: make run-tests

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Binaries from artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./artifacts/
      - name: Set Tag Version
        run: echo "VERSION=$(cat ./.github/version.txt)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.VERSION }}"
          release_name: "GoMQ ${{ env.VERSION }}: Initial Release"
          draft: true
          prerelease: true
      - name: Upload macOS Broker Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/broker-macos
          asset_name: broker-macos
          asset_content_type: application/octet-stream
      - name: Upload Linux Broker Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/broker-linux
          asset_name: broker-linux
          asset_content_type: application/octet-stream
      - name: Upload Windows Broker Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/broker.exe
          asset_name: broker.exe
          asset_content_type: application/octet-stream
      - name: Upload macOS CLI Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/cli-macos
          asset_name: cli-macos
          asset_content_type: application/octet-stream
      - name: Upload Linux CLI Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/cli-linux
          asset_name: cli-linux
          asset_content_type: application/octet-stream
      - name: Upload Windows CLI Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/cli.exe
          asset_name: cli.exe
          asset_content_type: application/octet-stream
